"""assistant chat history (QA round 2, feature B): compact rows, purged after N days

Revision ID: b00de379b8fb
Revises: c4a9e1f07b52
Create Date: 2026-10-03 19:24:37.926944
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b00de379b8fb'
down_revision: str | None = 'c4a9e1f07b52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_messages',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('conversation', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=True),
    sa.Column('batch_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assistant_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_messages'))
    )
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_messages_user_id_created_at'), ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping the table drops its indexes (MariaDB refuses to drop the FK's index first).
    op.drop_table('assistant_messages')
    # ### end Alembic commands ###
