"""import batches

Revision ID: 74483cbd79c0
Revises: a018c2a4833e
Create Date: 2026-09-27 19:57:09.053180
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '74483cbd79c0'
down_revision: str | None = 'a018c2a4833e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('kind', sa.Enum('ITEMS', 'STOCK', name='importkind', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('EXCEL', 'CSV', 'WORD', 'SCAN', 'TEXT', name='importsource', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'APPLIED', 'DISCARDED', name='batchstatus', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.Enum('OPENING', 'RECEIPT', 'ISSUE', 'TRANSFER', 'ADJUSTMENT', 'LOAN_OUT', 'LOAN_RETURN', name='doctype', native_enum=False, length=20), nullable=True),
    sa.Column('warehouse_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('person_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('result_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['applied_by_id'], ['users.id'], name=op.f('fk_import_batches_applied_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_import_batches_created_by_id_users')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_import_batches_person_id_persons')),
    sa.ForeignKeyConstraint(['result_document_id'], ['documents.id'], name=op.f('fk_import_batches_result_document_id_documents')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_import_batches_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_status'), ['status'], unique=False)

    op.create_table('import_lines',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=150), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'EXISTING_MATCH', 'CONFLICT', 'ERROR', 'IGNORED', name='linestatus', native_enum=False, length=20), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('match_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('resolution', sa.Enum('CREATE', 'MATCH', 'OVERWRITE', 'IGNORE', name='resolution', native_enum=False, length=20), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_lines_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_item_id'], ['items.id'], name=op.f('fk_import_lines_match_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_lines'))
    )
    with op.batch_alter_table('import_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_lines_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_lines_batch_id'))

    op.drop_table('import_lines')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_status'))

    op.drop_table('import_batches')
    # ### end Alembic commands ###
