"""ai providers

Revision ID: c515896fff65
Revises: 96e06baf359e
Create Date: 2026-09-27 20:42:32.663803
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c515896fff65'
down_revision: str | None = '96e06baf359e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('OPENAI', 'GROQ', 'HUGGINGFACE', 'OLLAMA', name='providerkind', native_enum=False, length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('stt_model', sa.String(length=200), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_ai_providers_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
