"""login lockout and audit approver

Revision ID: a018c2a4833e
Revises: 8cf386cd9d51
Create Date: 2026-09-27 17:35:36.890724
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a018c2a4833e'
down_revision: str | None = '8cf386cd9d51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_audit_log_approved_by_id_users'), 'users', ['approved_by_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_logins', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_logins')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_log_approved_by_id_users'), type_='foreignkey')
        batch_op.drop_column('approved_by_id')

    # ### end Alembic commands ###
