"""stocktakes

Revision ID: 96e06baf359e
Revises: 74483cbd79c0
Create Date: 2026-09-27 20:24:45.660823
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '96e06baf359e'
down_revision: str | None = '74483cbd79c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocktakes',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COUNTED', 'APPROVED', 'CANCELLED', name='stocktakestatus', native_enum=False, length=20), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('adjustment_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['adjustment_document_id'], ['documents.id'], name=op.f('fk_stocktakes_adjustment_document_id_documents')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_stocktakes_approved_by_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_stocktakes_category_id_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_stocktakes_created_by_id_users')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_stocktakes_submitted_by_id_users')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stocktakes_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocktakes')),
    sa.UniqueConstraint('number', name=op.f('uq_stocktakes_number'))
    )
    with op.batch_alter_table('stocktakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocktakes_status'), ['status'], unique=False)

    op.create_table('stocktake_lines',
    sa.Column('stocktake_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('system_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('counted_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('counted_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['counted_by_id'], ['users.id'], name=op.f('fk_stocktake_lines_counted_by_id_users')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_stocktake_lines_item_id_items')),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktakes.id'], name=op.f('fk_stocktake_lines_stocktake_id_stocktakes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocktake_lines')),
    sa.UniqueConstraint('stocktake_id', 'item_id', name=op.f('uq_stocktake_lines_stocktake_id_item_id'))
    )
    with op.batch_alter_table('stocktake_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocktake_lines_stocktake_id'), ['stocktake_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocktake_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocktake_lines_stocktake_id'))

    op.drop_table('stocktake_lines')
    with op.batch_alter_table('stocktakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocktakes_status'))

    op.drop_table('stocktakes')
    # ### end Alembic commands ###
