"""scheduled tasks

Revision ID: 986638137277
Revises: c515896fff65
Create Date: 2026-09-27 21:01:43.336565
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '986638137277'
down_revision: str | None = 'c515896fff65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('BACKUP', 'REPORT', name='taskkind', native_enum=False, length=20), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACTIVE', 'PAUSED', name='taskstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('machine', sa.String(length=128), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_ok', sa.Boolean(), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_scheduled_tasks_approved_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_scheduled_tasks_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
